# Book settings
title: Programming Reactive Systems
author: Vikram Bhatt
logo: logo.png

latex:
  latex_documents:
    targetname: book.tex

parse:
  myst_extended_syntax: true

html:
  favicon: images/favicon.ico
  comments:
    hypothesis: true

execute:
  execute_notebooks: cache

repository:
  url: https://github.com/hacker-eleos/scala-reactive-notes
  branch: main  # An optional branch, defaults to `master`
html:
  use_edit_page_button: true